name: Push Trigger Workflow

on:
  push:
  workflow_dispatch:

jobs:
  repo_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Show current folder
        run: pwd

      - name: Show all files
        run: ls -la

      - name: Print confirmation
        run: echo "This workflow can run manually and automatically on push"

      - name: this command is for running python file
        run: python hlo.py
