name: My_first_action_workflw

on:
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Print welcome
        run: echo "Welcome to GitHub Actions"

      - name: Step 2 - Show current folder
        run: pwd

      - name: Step 3 - List files
        run: ls

  
