name: Repo Info Workflow

on:
  workflow_dispatch:

jobs:
  repo-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Show current folder
        run: pwd

      - name: Show files in repository
        run: ls -la

      - name: Print success message
        run: echo "Repository code is now available in the runner"
